packages:
  - 'packages/*'
  - 'packages-deprecated/*'
  - 'demos'
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  iframe-resizer: true
minimumReleaseAgeExclude:
  - '@tiptap/y-tiptap@3.0.5'
  - '@tiptap/core@3.27.0'
  - '@tiptap/pm@3.27.0'
  - '@tiptap/y-tiptap@3.0.6'
overrides:
  '@rollup/pluginutils>picomatch': '2.3.2'
  '@octokit/action>undici': '6.24.1'
  'anymatch>picomatch': '2.3.2'
  'glob': '^10.5.0'
  'micromatch>picomatch': '2.3.2'
  'minimatch@^3.0.5': '3.1.4'
  'minimatch@^3.1.2': '3.1.4'
  'qs': '^6.14.1'
  'rollup': '4.60.1'
  'readdirp>picomatch': '2.3.2'
  'sass>immutable': '5.1.5'
  'terser-webpack-plugin>serialize-javascript': '7.0.5'
  'tinyglobby>picomatch': '4.0.4'
  'vitest>picomatch': '4.0.4'
patchedDependencies:
  '@changesets/assemble-release-plan@6.0.5': 'patches/@changesets__assemble-release-plan.patch'
  '@changesets/assemble-release-plan@6.0.9': 'patches/@changesets__assemble-release-plan@6.0.9.patch'
