blank_issues_enabled: false
contact_links:
  - name: New Feature Request
    url: https://github.com/ueberdosis/tiptap/discussions/new?category=feature-requests
    about: Interested in proposing a new feature for Tiptap? Submit your feature request here.
  - name: Help & Support
    url: https://github.com/ueberdosis/tiptap/discussions/new?category=questions-help
    about: Require assistance or have inquiries about using Tiptap? Ask your questions here.
  - name: Join our Discord
    url: https://discord.gg/WtJ49jGshW
    about: Interested in engaging with the Tiptap community? Join our Discord server.
  - name: Present your project
    url: https://github.com/ueberdosis/tiptap/discussions/new?category=showcase
    about: Developed something impressive using Tiptap? Share your project with the community here.
  - name: Present your Tiptap extensions
    url: https://github.com/ueberdosis/tiptap/discussions/new?category=community-extensions
    about: Created a Tiptap extension? Showcase your work to the community here.
