import { defineConfig } from 'vite-plus'
import { basePackConfig, tsupCompatibleExtensions } from '../../pack.config.mjs'

/** Keep in sync with the `exports` map in package.json. */
const subExports = [
  'ai-toolkit',
  'ai-toolkit/streaming-reveal',
  'extensions/audio',
  'extensions/background-color',
  'extensions/blockquote',
  'extensions/bold',
  'extensions/bubble-menu',
  'extensions/character-count',
  'extensions/code',
  'extensions/code-block',
  'extensions/code-block-lowlight',
  'extensions/collaboration',
  'extensions/collaboration-caret',
  'extensions/color',
  'extensions/details',
  'extensions/document',
  'extensions/drag-handle',
  'extensions/drop-cursor',
  'extensions/emoji',
  'extensions/emoji/data',
  'extensions/file-handler',
  'extensions/find-and-replace',
  'extensions/floating-menu',
  'extensions/focus',
  'extensions/font-family',
  'extensions/font-size',
  'extensions/gap-cursor',
  'extensions/hard-break',
  'extensions/heading',
  'extensions/highlight',
  'extensions/horizontal-rule',
  'extensions/image',
  'extensions/invisible-characters',
  'extensions/italic',
  'extensions/line-height',
  'extensions/link',
  'extensions/list',
  'extensions/mathematics',
  'extensions/mention',
  'extensions/node-range',
  'extensions/paragraph',
  'extensions/placeholder',
  'extensions/ruby-text',
  'extensions/selection',
  'extensions/strike',
  'extensions/subscript',
  'extensions/suggestion',
  'extensions/superscript',
  'extensions/table',
  'extensions/table-of-contents',
  'extensions/text',
  'extensions/text-align',
  'extensions/text-style',
  'extensions/trailing-node',
  'extensions/twitch',
  'extensions/typography',
  'extensions/underline',
  'extensions/undo-redo',
  'extensions/unique-id',
  'extensions/youtube',
  'html',
  'html/server',
  'kits/list',
  'kits/starter',
  'kits/table',
  'kits/text-style',
  'markdown',
  'pm/changeset',
  'pm/commands',
  'pm/dropcursor',
  'pm/gapcursor',
  'pm/history',
  'pm/inputrules',
  'pm/keymap',
  'pm/model',
  'pm/schema-list',
  'pm/state',
  'pm/tables',
  'pm/transform',
  'pm/view',
  'static-renderer',
]

export default defineConfig({
  pack: [
    {
      ...basePackConfig(),
      entry: ['src/index.ts'],
      outDir: 'dist',
    },
    {
      ...basePackConfig(),
      entry: ['src/jsx-runtime.ts'],
      outDir: 'dist/jsx-runtime',
      clean: false,
    },
    // One config per subpath. Sharing a config collapses the declaration file
    // names, because dts output is named from the entry basename.
    ...subExports.map(subpath => ({
      ...basePackConfig(),
      entry: [`src/${subpath}/index.ts`],
      outDir: `dist/${subpath}`,
      clean: false,
      // self-references and third-party deps stay external so nothing is duplicated
      deps: { neverBundle: [/^[^./]/] },
      outExtensions: tsupCompatibleExtensions,
    })),
  ],
})
