import { defineConfig } from 'vite-plus'
import { basePackConfig, tsupCompatibleExtensions } from '../../pack.config.mjs'

/** Keep in sync with the `exports` map in package.json. */
const subExports = [
  'extensions/background-color',
  'extensions/blockquote',
  'extensions/bold',
  'extensions/bubble-menu',
  'extensions/character-count',
  'extensions/code',
  'extensions/code-block',
  'extensions/color',
  'extensions/document',
  'extensions/drop-cursor',
  'extensions/floating-menu',
  'extensions/focus',
  'extensions/font-family',
  'extensions/font-size',
  'extensions/gap-cursor',
  'extensions/hard-break',
  'extensions/heading',
  'extensions/horizontal-rule',
  'extensions/image',
  'extensions/italic',
  'extensions/line-height',
  'extensions/link',
  'extensions/list',
  'extensions/paragraph',
  'extensions/placeholder',
  'extensions/selection',
  'extensions/strike',
  'extensions/table',
  'extensions/text',
  'extensions/text-style',
  'extensions/trailing-node',
  'extensions/underline',
  'extensions/undo-redo',
  'kits/list',
  'kits/starter',
  'kits/table',
  'kits/text-style',
  'pm/changeset',
  'pm/commands',
  'pm/dropcursor',
  'pm/gapcursor',
  'pm/history',
  'pm/inputrules',
  'pm/keymap',
  'pm/model',
  'pm/schema-list',
  'pm/state',
  'pm/tables',
  'pm/transform',
  'pm/view',
]

export default defineConfig({
  pack: [
    {
      ...basePackConfig(),
      entry: ['src/index.ts'],
      outDir: 'dist',
    },
    {
      ...basePackConfig(),
      entry: ['src/jsx-runtime.ts'],
      outDir: 'dist/jsx-runtime',
    },
    ...subExports.map(subpath => ({
      ...basePackConfig(),
      entry: [`src/${subpath}/index.ts`],
      outDir: `dist/${subpath}`,
      clean: false,
      // self-references and third-party deps stay external so nothing is duplicated
      deps: { neverBundle: [/^[^./]/] },
      outExtensions: tsupCompatibleExtensions,
    })),
  ],
})
